name: test_pages

# Controls when the workflow will run
on:
  # Triggers only on pushes and pull_requests
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Able to be run on command
  workflow_dispatch:

jobs:

  test_pages:
    # Runner for job
    runs-on: ubuntu-latest

    # Steps for job
    steps:
      # Checks-out repo
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run command
      - name: Run python tests
        run: pytest